// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsM3tRKInDeLaLYuilRvIUQjelf-K2X4',
    appId: '1:902614801662:web:d520641c3d77cfe60459af',
    messagingSenderId: '902614801662',
    projectId: 'flutterauth-cfde8',
    authDomain: 'flutterauth-cfde8.firebaseapp.com',
    storageBucket: 'flutterauth-cfde8.appspot.com',
    measurementId: 'G-GCZ518ZD2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdZrRrFyNwaMmz4dsij748QKmmYqXBj5s',
    appId: '1:902614801662:android:0d663d80df7777ae0459af',
    messagingSenderId: '902614801662',
    projectId: 'flutterauth-cfde8',
    storageBucket: 'flutterauth-cfde8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMnsDFOpFbpfwBb3tUkXBdv5gmvM5NzI',
    appId: '1:902614801662:ios:32006517afb1fdba0459af',
    messagingSenderId: '902614801662',
    projectId: 'flutterauth-cfde8',
    storageBucket: 'flutterauth-cfde8.appspot.com',
    iosBundleId: 'com.example.flutterSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyMnsDFOpFbpfwBb3tUkXBdv5gmvM5NzI',
    appId: '1:902614801662:ios:54d10ff815722b3e0459af',
    messagingSenderId: '902614801662',
    projectId: 'flutterauth-cfde8',
    storageBucket: 'flutterauth-cfde8.appspot.com',
    iosBundleId: 'com.example.flutterSignin.RunnerTests',
  );
}
